version: "3"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.12.13
    ports:
      - "443:443"
      - "4566:4566"
    env_file:
      - .env
    environment:
      - SERVICES=lambda, s3, ec2
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - TMPDIR=/private$TMPDIR
      - LAMBDA_DOCKER_NETWORK="host"
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  python-env:
    container_name: "python-env"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
