name: CI Backend
on:
  [workflow_dispatch, push]

concurrency: ci-backend-${{ github.ref }}

jobs:

  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: run gitleaks docker
        run: |
          docker run -v ${PWD}:/path zricethezav/gitleaks:latest detect --source="/path/" -v -l debug --no-git
  
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog
        run: |
          docker run -v ${PWD}:/truffle trufflesecurity/trufflehog:latest filesystem --directory="/truffle/"


  # unit-tests-and-coverage:
  #   name: Tests and coverage
  #   runs-on: ubuntu-latest
  #   needs: [gitleaks]
  #   env:
  #     FLASK_ENV: development
  #   steps:
  #     - name: checkout git repository
  #       uses: actions/checkout@v3

  #     - name: Setup Python 3.8
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: "3.8"

  #     - name: Install dependencies
  #       run: pip install -r requirements.txt

      # - name: Execute unit tests and generate coverage file
      #   run: |
      #     bash ./scripts/run_test.sh


      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
        with:
          pytest-coverage: pytest-coverage.txt
        
  lint:
    name: Lint
    runs-on: ubuntu-latest
    #env:
    needs: [gitleaks]
    #  FLASK_ENV: development
    steps:
      - name: checkout git repository
        uses: actions/checkout@v3

      - name: Setup Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint
        run: pylint ./lambda/*.py

  security-checks:
    runs-on: ubuntu-latest
    needs: [gitleaks]
    name: Pycharm-security check
    steps:
      - name: checkout git repository
        uses: actions/checkout@v3

      - name: Run PyCharm Security
        uses: tonybaloney/pycharm-security@master

  docker-grype-project:
    name: Grype (Anchore) Project Scan
    needs: [gitleaks]
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Scan current project with Grype (Anchore)
        id: scan-project
        uses: anchore/scan-action@v3
        with:
          path: "."
          fail-build: false
      # Advanced Security in Github must be enabled for this repository to upload report.
      # - name: upload Anchore scan SARIF report
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: ${{ steps.scan-project.outputs.sarif }}